# Generated by Django 4.2.11 on 2025-10-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugevent',
            name='description',
            field=models.TextField(blank=True, help_text='AI-generated professional description explaining the reason for the event (withdrawal/suspension/registration)', null=True),
        ),
    ]
